name: Android APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK with Version and Date
        run: |
          mkdir -p release-apk
          DATE=$(date +"%Y-%m-%d_%H-%M")
          APK_NAME="MarketSignal_v1.0_${DATE}.apk"
          cp app/build/outputs/apk/release/app-release.apk release-apk/$APK_NAME
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APK_NAME }}
          path: release-apk/${{ env.APK_NAME }}
