name: Android APK Build

on:
  push:
    branches:
      - main   # जब भी main branch पर push करेंगे build होगा
  workflow_dispatch:  # Manual run का option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Get Version Name
        id: version
        run: |
          VERSION_NAME=$(./gradlew -q printVersionName)
          DATE=$(date +"%Y-%m-%d_%H-%M")
          echo "APK_NAME=MarketSignal_v${VERSION_NAME}_${DATE}.apk" >> $GITHUB_ENV

      - name: Rename APK
        run: |
          mkdir -p release-apk
          cp app/build/outputs/apk/release/app-release.apk release-apk/$APK_NAME

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APK_NAME }}
          path: release-apk/${{ env.APK_NAME }}
          
